# Generated by Django 4.2.17 on 2025-01-03 02:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('date_of_passing', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.CharField(blank=True, choices=[('severe_anemia', 'Severe Anemia'), ('thrombosis', 'Thrombosis (Blood clot)'), ('internal_bleeding', 'Internal Bleeding'), ('organ_failure', 'Organ Failure'), ('infection', 'Infection'), ('treatment_complications', 'Treatment Complications')], max_length=50, null=True)),
                ('other_cause_of_death', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('spayed_neutered', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='vet_docs/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.JSONField()),
                ('duration', models.CharField(choices=[('LT_1WEEK', '< 1 Week'), ('BETWEEN_1_2_WEEKS', '1-2 Weeks'), ('BETWEEN_3_5_WEEKS', '3-4 Weeks'), ('OVER_5_WEEKS', '5+ Weeks')], max_length=30)),
                ('RBC', models.IntegerField(blank=True, null=True)),
                ('RET', models.IntegerField(blank=True, null=True)),
                ('PCV', models.IntegerField(blank=True, null=True)),
                ('treatment_adjusted', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.pet')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_life', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10)),
                ('personality_changes', models.CharField(choices=[('significant', 'Yes, significantly'), ('slight', 'Yes, slightly'), ('no', 'No')], max_length=15)),
                ('recurrence', models.BooleanField(default=False)),
                ('resources', models.TextField(blank=True, null=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_method', multiselectfield.db.fields.MultiSelectField(choices=[('routine_bloodwork', 'Routine blood work'), ('vet_visit_symptoms', 'Symptoms presented during another vet visit'), ('emergency_visit', 'Emergency vet visit due to acute symptoms'), ('other', 'Other')], max_length=50)),
                ('diagnostic_date', models.DateField()),
                ('RBC', models.IntegerField(blank=True, null=True)),
                ('initial_symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('lethargy', 'Lethargy'), ('weakness', 'Weakness'), ('pale_gums', 'Pale gums'), ('fever', 'Fever'), ('loss_appetite', 'Loss of appetite'), ('vomiting', 'Vomiting'), ('diarrhea', 'Diarrhea'), ('jaundice', 'Jaundice'), ('difficulty_breathing', 'Difficulty breathing'), ('other', 'Other')], max_length=101)),
                ('other_initial_symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.pet')),
            ],
        ),
    ]
