# Generated by Django 4.2.17 on 2024-12-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateTimeField()),
                ('passing_date', models.DateTimeField()),
                ('breed', models.TextField(default='Default content')),
                ('diagnosis_date', models.DateTimeField()),
                ('vaccinations', models.TextField()),
                ('rbc_1', models.IntegerField()),
                ('pcv_1', models.IntegerField()),
                ('ret_1', models.IntegerField()),
                ('b_trans1', models.BooleanField()),
                ('prescriptions', models.TextField()),
            ],
        ),
    ]
