# Generated by Django 4.2.17 on 2025-01-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='RBC',
        ),
    ]
