# Generated by Django 4.2.17 on 2024-12-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
