# Generated by Django 4.2.17 on 2024-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_pet_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
