# Generated by Django 4.2.17 on 2024-12-28 05:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_pet_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='b_trans1',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pcv_1',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='rbc_1',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='ret_1',
        ),
        migrations.AddField(
            model_name='pet',
            name='blood_transfusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='num_transfusions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='prescriptions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('antibiotic', 'Choice 1'), ('painkiller', 'Painkiller'), ('steroid', 'Steroid'), ('immunosuppressant', 'Immunosuppressant')], max_length=47, null=True),
        ),
    ]
