# Generated by Django 4.2.17 on 2024-12-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_pet_b_trans1_remove_pet_pcv_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='prescriptions',
            field=models.CharField(blank=True, choices=[('antibiotic', 'Choice 1'), ('painkiller', 'Painkiller'), ('steroid', 'Steroid'), ('immunosuppressant', 'Immunosuppressant')], max_length=20, null=True),
        ),
    ]
