# Generated by Django 4.2.17 on 2024-12-28 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_pet_prescriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='prescriptions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('antibiotic', 'Choice 1'), ('painkiller', 'Painkiller'), ('steroid', 'Steroid'), ('immunosuppressant', 'Immunosuppressant')], max_length=20, null=True),
        ),
    ]
