# Generated by Django 4.2.17 on 2024-12-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_pet_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='azathioprine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='cyclosporine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='dexamethasone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='doxycycline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='mycophenolate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='other_medications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='prednisone',
            field=models.BooleanField(default=False),
        ),
    ]
