# Generated by Django 4.2.17 on 2024-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_pet_azathioprine_pet_cyclosporine_pet_dexamethasone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='additional_information',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
