# Generated by Django 4.2.17 on 2024-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_pet_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passing_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
