# Generated by Django 4.2.17 on 2024-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_pet_passing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
